--[[
	Assets
	Image ids lifted out of the UI pack.

	GENERATED by tools/extract_assets.py -- do not hand-edit `Assets.Pack`,
	it is overwritten wholesale on the next run. Put anything you choose
	by hand in `Assets.UI` at the bottom, which is never regenerated.

	These are already uploaded to Roblox, so they work immediately -- no
	upload and no moderation wait, unlike raw PNGs.
]]

local Assets = {}

--[[ Everything found in the pack, grouped by the screen it came from. ]]
Assets.Pack = {
	DailyRewards = {
		Aura = "rbxassetid://121608928706547",
		Base = "rbxassetid://124255786713749",
		Base2 = "rbxassetid://118936407927971",
		Base3 = "rbxassetid://85418881543537",
		Base4 = "rbxassetid://98481085949338",
		CashIcon = "rbxassetid://139378165309957",
		CheckIcon = "rbxassetid://89889146498788",
		DarkOverlay = "rbxassetid://79940753048188",
		DragonCannelloniicon1_diff_1 = "rbxassetid://101018319750940",
		GreenOverlay = "rbxassetid://131518255087677",
		ShadowOverlay = "rbxassetid://114146673464671",
		ShadowOverlay2 = "rbxassetid://126543551582765",
		ShadowOverlay3 = "rbxassetid://85949868598254",
		cButton = "rbxassetid://127200142470188",
		drBase = "rbxassetid://102224329662898",
		drHeader = "rbxassetid://121284947462819",
	},
	Discover = {
		Bar = "rbxassetid://103548828587741",
		Bar2 = "rbxassetid://99306115753624",
		Bar3 = "rbxassetid://121693297337466",
		Bar4 = "rbxassetid://108176187923282",
		Bar5 = "rbxassetid://116324292388758",
		Fill = "rbxassetid://107892662564811",
		Fill2 = "rbxassetid://138849968386794",
		Fill3 = "rbxassetid://118566633351280",
		Fill4 = "rbxassetid://126379982181295",
		Fill5 = "rbxassetid://117450568304521",
		Fill6 = "rbxassetid://113712283803614",
		dBase = "rbxassetid://95282639208407",
	},
	Index = {
		Aura = "rbxassetid://114552234259657",
		Base = "rbxassetid://139534546293459",
		Base10 = "rbxassetid://127631664845759",
		Base11 = "rbxassetid://80880187294365",
		Base2 = "rbxassetid://112103934998238",
		Base3 = "rbxassetid://105847562945222",
		Base4 = "rbxassetid://82227029059241",
		Base5 = "rbxassetid://96058623308571",
		Base6 = "rbxassetid://101109265270105",
		Base7 = "rbxassetid://92762963897240",
		Base8 = "rbxassetid://78777511179772",
		Base9 = "rbxassetid://105945070177153",
		Button = "rbxassetid://125305160060545",
		Button2 = "rbxassetid://85951933438459",
		Button3 = "rbxassetid://104901976374919",
		Button4 = "rbxassetid://71428817557187",
		Button5 = "rbxassetid://93785431393688",
		Button6 = "rbxassetid://82654490140543",
		Shine = "rbxassetid://121438339833888",
		Shine2 = "rbxassetid://138662967124111",
		Shine3 = "rbxassetid://139695536195860",
		Shine4 = "rbxassetid://100784129138881",
		Shine5 = "rbxassetid://126304733973319",
		Shine6 = "rbxassetid://111301692225778",
		Shine7 = "rbxassetid://138152983354821",
		Shine8 = "rbxassetid://71032477721021",
		Shine9 = "rbxassetid://71729316050755",
		cButton = "rbxassetid://127200142470188",
	},
	LeftBottomBar = {
		IconBtn01 = "rbxassetid://140711362394771",
		IconBtn02 = "rbxassetid://75788757904847",
		IconBtn03 = "rbxassetid://136181632676770",
		IconBtn04 = "rbxassetid://76133612592157",
		IconBtn05 = "rbxassetid://86508491861523",
	},
	LeftSide = {
		BackpackIcon = "rbxassetid://83054147083642",
		BookIcon = "rbxassetid://82105660031779",
		GiftIcon = "rbxassetid://108436736039687",
		RebirthIcon = "rbxassetid://120692448519497",
		ShopIcon = "rbxassetid://113630023666712",
		hBase = "rbxassetid://136301508937099",
	},
	PlaytimeRewards = {
		Aura = "rbxassetid://117012608454818",
		Base = "rbxassetid://127640857337371",
		Base2 = "rbxassetid://134530458148666",
		Base3 = "rbxassetid://70388458939030",
		Button = "rbxassetid://85969836516135",
		CashIcon = "rbxassetid://108122956922773",
		CheckIcon = "rbxassetid://89889146498788",
		RbxIcon = "rbxassetid://125952260799634",
		ShadowOverlay = "rbxassetid://114146673464671",
		cButton = "rbxassetid://127200142470188",
	},
	Rebirth = {
		ArrowIcon = "rbxassetid://128693116040388",
		Aura = "rbxassetid://83133530552333",
		Bar = "rbxassetid://114649080560013",
		Base = "rbxassetid://71121353996614",
		Base2 = "rbxassetid://80447737473155",
		Button = "rbxassetid://104250537735153",
		Button2 = "rbxassetid://139902667026944",
		CashIcon01 = "rbxassetid://140096093631013",
		Fill = "rbxassetid://84904424597389",
		RbxIcon = "rbxassetid://86084918706765",
		cButton = "rbxassetid://127200142470188",
		reBase = "rbxassetid://119033862707961",
	},
	Rewards = {
		Aura = "rbxassetid://120699885675228",
		Base = "rbxassetid://108897236895341",
		Base2 = "rbxassetid://137754688757713",
		Base3 = "rbxassetid://118486815415041",
		CashIcon01 = "rbxassetid://91844143488634",
		Main = "rbxassetid://132566729777883",
		Main2 = "rbxassetid://103070176466116",
		WatchIcon = "rbxassetid://99972927646587",
		cButton = "rbxassetid://127200142470188",
	},
}

--[[
	The curated slots the game actually reads. Kept separate from Pack so a
	regenerated pack can never silently change what the UI displays.
	nil means 'still using the text glyph fallback'.
]]
Assets.UI = {
	money = Assets.Pack.PlaytimeRewards and Assets.Pack.PlaytimeRewards.CashIcon or nil,
	close = Assets.Pack.DailyRewards and Assets.Pack.DailyRewards.cButton or nil,
	aura = Assets.Pack.DailyRewards and Assets.Pack.DailyRewards.Aura or nil,
	buttonBase = Assets.Pack.LeftSide and Assets.Pack.LeftSide.hBase or nil,
	barTrack = nil,
	barFill = nil,

	-- filled in once the icon PNGs are uploaded (see assets/icons/_upload)
	tileMine = nil,
	tileGem = nil,
	padLocked = nil,
	equipBest = nil,
}

function Assets.get(slot)
	return Assets.UI[slot]
end

return Assets
