#!/usr/bin/env python3
"""
extract_assets.py -- turn a UI-pack .rbxmx into src/.../Shared/Assets.lua

The pack's images are ALREADY uploaded to Roblox (they arrive as rbxassetid://
references), so unlike the icon PNGs there's no upload step -- they just need
lifting out of the model file and into a registry the UI can read.

    python tools/extract_assets.py "C:\\path\\to\\YourUiPack!.rbxmx"

Re-run it if you get a new pack; it overwrites Assets.lua wholesale. Anything
hand-written belongs in the CURATED table inside Assets.lua, not here.
"""

import collections
import pathlib
import re
import sys
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "ReplicatedStorage" / "Shared" / "Assets.lua"

IMAGE_PROPS = ("Image", "HoverImage", "PressedImage")


def props(item):
    p = item.find("Properties")
    return p if p is not None else ET.Element("Properties")


def sval(item, name):
    n = props(item).find("string[@name='%s']" % name)
    return n.text if n is not None and n.text else ""


def content(item, name):
    c = props(item).find("Content[@name='%s']" % name)
    if c is not None:
        u = c.find("url")
        if u is not None and u.text:
            return u.text.strip()
    s = props(item).find("string[@name='%s']" % name)
    return s.text.strip() if s is not None and s.text else ""


def name_of(item):
    return sval(item, "Name") or item.get("class", "?")


def lua_key(text):
    """A safe Lua identifier, or None if it can't be made into one."""
    key = re.sub(r"[^A-Za-z0-9_]", "_", text).strip("_")
    key = re.sub(r"_+", "_", key)
    if not key or key[0].isdigit():
        key = "k" + key
    return key


def main():
    src = pathlib.Path(sys.argv[1] if len(sys.argv) > 1
                       else r"C:\Users\jljoh\Downloads\YourUiPack!.rbxmx")
    if not src.is_file():
        print("not found: %s" % src, file=sys.stderr)
        return 1

    root = ET.parse(src).getroot()
    # screen -> { elementName -> assetId }
    screens = collections.defaultdict(dict)
    seen_ids = set()

    def walk(node, trail):
        for item in node.findall("Item"):
            nm = name_of(item)
            here = trail + [nm]
            for prop in IMAGE_PROPS:
                val = content(item, prop)
                if val and "rbxassetid" in val:
                    # trail[0] is the ScreenGui, trail[1] is the screen
                    screen = here[1] if len(here) > 1 else "Root"
                    key = nm if prop == "Image" else "%s_%s" % (nm, prop)
                    # de-dup within a screen: Slot01/Base and Slot02/Base collide
                    base, n = key, 2
                    while key in screens[screen] and screens[screen][key] != val:
                        key = "%s%d" % (base, n)
                        n += 1
                    screens[screen][key] = val
                    seen_ids.add(val)
            walk(item, here)

    walk(root, [])

    lines = []
    lines.append("--[[")
    lines.append("\tAssets")
    lines.append("\tImage ids lifted out of the UI pack.")
    lines.append("")
    lines.append("\tGENERATED by tools/extract_assets.py -- do not hand-edit `Assets.Pack`,")
    lines.append("\tit is overwritten wholesale on the next run. Put anything you choose")
    lines.append("\tby hand in `Assets.UI` at the bottom, which is never regenerated.")
    lines.append("")
    lines.append("\tThese are already uploaded to Roblox, so they work immediately -- no")
    lines.append("\tupload and no moderation wait, unlike raw PNGs.")
    lines.append("]]")
    lines.append("")
    lines.append("local Assets = {}")
    lines.append("")
    lines.append("--[[ Everything found in the pack, grouped by the screen it came from. ]]")
    lines.append("Assets.Pack = {")

    for screen in sorted(screens):
        entries = screens[screen]
        lines.append("\t%s = {" % lua_key(screen))
        for key in sorted(entries):
            lines.append('\t\t%s = "%s",' % (lua_key(key), entries[key]))
        lines.append("\t},")
    lines.append("}")
    lines.append("")
    lines.append("--[[")
    lines.append("\tThe curated slots the game actually reads. Kept separate from Pack so a")
    lines.append("\tregenerated pack can never silently change what the UI displays.")
    lines.append("\tnil means 'still using the text glyph fallback'.")
    lines.append("]]")
    lines.append("Assets.UI = {")
    lines.append("\tmoney = Assets.Pack.PlaytimeRewards and Assets.Pack.PlaytimeRewards.CashIcon or nil,")
    lines.append("\tclose = Assets.Pack.DailyRewards and Assets.Pack.DailyRewards.cButton or nil,")
    lines.append("\taura = Assets.Pack.DailyRewards and Assets.Pack.DailyRewards.Aura or nil,")
    lines.append("\tbuttonBase = Assets.Pack.LeftSide and Assets.Pack.LeftSide.hBase or nil,")
    lines.append("\tbarTrack = nil,")
    lines.append("\tbarFill = nil,")
    lines.append("")
    lines.append("\t-- filled in once the icon PNGs are uploaded (see assets/icons/_upload)")
    lines.append("\ttileMine = nil,")
    lines.append("\ttileGem = nil,")
    lines.append("\tpadLocked = nil,")
    lines.append("\tequipBest = nil,")
    lines.append("}")
    lines.append("")
    lines.append("function Assets.get(slot)")
    lines.append("\treturn Assets.UI[slot]")
    lines.append("end")
    lines.append("")
    lines.append("return Assets")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")

    print("wrote %s" % OUT.relative_to(ROOT))
    print("  %d screens, %d unique image ids" % (len(screens), len(seen_ids)))
    for screen in sorted(screens):
        print("    %-20s %3d images" % (screen, len(screens[screen])))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
